### ISSUE TITLE
Acknowledgement

### ISSUE THREAD

**Issue by Maumagnaguagno** [pravj/x3030#1]
Hi @pravj, 

I just discovered you used my map generator, cool :smiley:.
Could you please add a link to my repo in your README?
If you do I will link your repo in Map generator's README.
And if you know about anybody else using it, please let me know.

Also feel free to open an issue/make a pull request and force me to add a JSON output.

**Comment by pravj** [comment]
Hi @Maumagnaguagno,

Ohh, I have given the reference in the source code. It's not proper, though. Sorry for that.
I will add the link in README right away.

I will send a pull request this weekend. Keeping it open.

**Comment by pravj** [comment]
Just added the reference in the commit https://github.com/pravj/x3030/commit/685ba79f94e869900833b9ecd974ad908b1dd00c. :smile:

**Comment by Maumagnaguagno** [comment]
Great, I added your project to Map generator's README :smile:.
I am sorry if I forced you to put a link, but it is not everyday that one of my projects is used and this is the way I found (after I saw that you opened an issue on 3030 to link both projects).
I saw that you had already added a reference in the source, but I much prefer a link.
Now people can see that our projects are connected and that it was your idea to pack a lot of maps in a single JSON (otherwise they would never discover what you modified).

And you could have said you wanted to use my project, it would made me a lot happier.
Sometimes I think if someone else is ever going to use that last commit, and here you are :smiley:.

You can close this issue now.
Thanks

**Comment by pravj** [comment]
No, you didn't force me, not at all.

I should have done it right while developing, but I was in a hurry as that bug was getting patched.

Thanks for developing the map generator. :+1: 

Closing it then, I will work on the Pull Request as soon as I'm free.
